/*
 * asciixlate --- UTF-8 to ASCII transliteration filter with a local rule file.
 *
 * Self-contained: no libiconv, no gconv, no runtime data files. The
 * transliteration table is generated by mktable.py and pinned into
 * translit_table.h, so output is byte-identical on Darwin, Linux and NetBSD.
 *
 * See --manual for the full manual. Build: cc -O2 -o asciixlate asciixlate.c
 *
 * (c) 2026 George Georgalis <george@iuxta.com>
 */

#if !defined(_XOPEN_SOURCE)
#define _XOPEN_SOURCE 700
#endif
#if defined(__APPLE__) || defined(__NetBSD__)
#define _DARWIN_C_SOURCE 1
#define _NETBSD_SOURCE 1
#endif

#include <sys/stat.h>
#include <sys/types.h>

#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "translit_table.h"

#define PROG "asciixlate"
#define VERSION "2.0.0"

#define DEFAULT_MARKER "??"
#define DEFAULT_MAX_SIZE (64u * 1024u * 1024u)
#define BINARY_SNIFF 8192          /* bytes examined for NUL */
#define CFG_MAX_KEY 64             /* bytes in a multi-codepoint key */
#define CFG_MAX_REPL 256

/* exit status */
#define EX_OK 0
#define EX_USAGE 1                 /* usage, config, or I/O failure */
#define EX_UNMAPPED 2              /* --strict and something was unmapped */

/* ---------------------------------------------------------------- state -- */

typedef struct {                   /* single-code-point rule */
    uint32_t cp;
    const char *repl;              /* NUL-terminated; may point into rodata */
    uint16_t len;
    uint8_t used;
} Slot;

typedef struct {                   /* multi-code-point (byte string) rule */
    unsigned char key[CFG_MAX_KEY];
    size_t key_len;
    char *repl;
    size_t repl_len;
} MultiRule;

typedef struct {
    Slot *slot;
    size_t mask;                   /* table size - 1, power of two */
    size_t count;

    MultiRule *multi;              /* sorted by descending key_len */
    size_t multi_n, multi_cap;
    uint8_t multi_first[256];      /* first-byte bitmap for the fast path */

    uint8_t ascii_mapped[128];     /* an ASCII code point carries a rule */
} Table;

typedef struct {                   /* counters for one file */
    size_t bytes_in, bytes_out;
    size_t replaced;               /* rule or table hits */
    size_t unmapped;               /* no mapping; marker emitted */
    size_t invalid;                /* malformed UTF-8 bytes */
} Stats;

typedef struct {                   /* unmapped code point census for --report */
    uint32_t cp;
    size_t n;
} Census;

static const char *marker = DEFAULT_MARKER;
static size_t marker_len = 2;
static int opt_verbose, opt_quiet, opt_strict, opt_keep, opt_inplace;
static int opt_dryrun, opt_report, opt_allow_binary;
static unsigned long opt_max_size = DEFAULT_MAX_SIZE;
static const char *opt_output;

static Census *census;
static size_t census_n, census_cap;

/* ------------------------------------------------------------ diagnostic -- */

static void warnx_(const char *fmt, ...)
{
    va_list ap;
    fprintf(stderr, "%s: ", PROG);
    va_start(ap, fmt);
    vfprintf(stderr, fmt, ap);
    va_end(ap);
    fputc('\n', stderr);
}

static void fatal(const char *fmt, ...)
{
    va_list ap;
    fprintf(stderr, "%s: ", PROG);
    va_start(ap, fmt);
    vfprintf(stderr, fmt, ap);
    va_end(ap);
    fputc('\n', stderr);
    exit(EX_USAGE);
}

static void *xmalloc(size_t n)
{
    void *p = malloc(n ? n : 1);
    if (!p) fatal("out of memory");
    return p;
}

static void *xrealloc(void *p, size_t n)
{
    void *q = realloc(p, n ? n : 1);
    if (!q) fatal("out of memory");    /* p is leaked, but we exit */
    return q;
}

static char *xstrndup(const char *s, size_t n)
{
    char *p = xmalloc(n + 1);
    memcpy(p, s, n);
    p[n] = '\0';
    return p;
}

/* ------------------------------------------------------------------ utf8 -- */

/*
 * Decode one code point at p (p < end). On success returns bytes consumed
 * (1..4) and sets *cp. On a malformed sequence returns 0 and leaves *cp
 * undefined; the caller advances by one byte and emits the marker.
 */
static size_t utf8_decode(const unsigned char *p, const unsigned char *end,
                          uint32_t *cp)
{
    unsigned c = *p, need;
    uint32_t v;

    if (c < 0x80) { *cp = c; return 1; }
    if ((c & 0xE0) == 0xC0) { need = 2; v = c & 0x1Fu; }
    else if ((c & 0xF0) == 0xE0) { need = 3; v = c & 0x0Fu; }
    else if ((c & 0xF8) == 0xF0) { need = 4; v = c & 0x07u; }
    else return 0;

    if ((size_t)(end - p) < need) return 0;
    for (unsigned i = 1; i < need; i++) {
        if ((p[i] & 0xC0) != 0x80) return 0;
        v = (v << 6) | (p[i] & 0x3Fu);
    }
    if (need == 2 && v < 0x80) return 0;
    if (need == 3 && (v < 0x800 || (v >= 0xD800 && v <= 0xDFFF))) return 0;
    if (need == 4 && (v < 0x10000 || v > 0x10FFFF)) return 0;
    *cp = v;
    return need;
}

static size_t utf8_encode(uint32_t cp, unsigned char *out)
{
    if (cp < 0x80) { out[0] = (unsigned char)cp; return 1; }
    if (cp < 0x800) {
        out[0] = (unsigned char)(0xC0 | (cp >> 6));
        out[1] = (unsigned char)(0x80 | (cp & 0x3F));
        return 2;
    }
    if (cp < 0x10000) {
        out[0] = (unsigned char)(0xE0 | (cp >> 12));
        out[1] = (unsigned char)(0x80 | ((cp >> 6) & 0x3F));
        out[2] = (unsigned char)(0x80 | (cp & 0x3F));
        return 3;
    }
    out[0] = (unsigned char)(0xF0 | (cp >> 18));
    out[1] = (unsigned char)(0x80 | ((cp >> 12) & 0x3F));
    out[2] = (unsigned char)(0x80 | ((cp >> 6) & 0x3F));
    out[3] = (unsigned char)(0x80 | (cp & 0x3F));
    return 4;
}

/* ----------------------------------------------------------------- table -- */

static size_t hash_cp(uint32_t cp, size_t mask)
{
    cp *= 2654435761u;             /* Knuth multiplicative */
    return (cp >> 11) & mask;
}

static void table_init(Table *t, size_t hint)
{
    size_t n = 64;
    while (n < hint * 2) n <<= 1;
    t->slot = xmalloc(n * sizeof *t->slot);
    memset(t->slot, 0, n * sizeof *t->slot);
    t->mask = n - 1;
    t->count = 0;
    t->multi = NULL;
    t->multi_n = t->multi_cap = 0;
    memset(t->multi_first, 0, sizeof t->multi_first);
    memset(t->ascii_mapped, 0, sizeof t->ascii_mapped);
}

/* repl must outlive the table (rodata or heap owned elsewhere) */
static void table_set(Table *t, uint32_t cp, const char *repl, size_t len)
{
    size_t i = hash_cp(cp, t->mask);
    while (t->slot[i].used) {
        if (t->slot[i].cp == cp) break;
        i = (i + 1) & t->mask;
    }
    if (!t->slot[i].used) { t->slot[i].used = 1; t->count++; }
    t->slot[i].cp = cp;
    t->slot[i].repl = repl;
    t->slot[i].len = (uint16_t)len;
    if (cp < 128) t->ascii_mapped[cp] = 1;
}

static const Slot *table_get(const Table *t, uint32_t cp)
{
    size_t i = hash_cp(cp, t->mask);
    while (t->slot[i].used) {
        if (t->slot[i].cp == cp) return &t->slot[i];
        i = (i + 1) & t->mask;
    }
    return NULL;
}

static void table_load_defaults(Table *t)
{
    for (size_t i = 0; i < TRANSLIT_TABLE_N; i++)
        table_set(t, translit_table[i].cp, translit_table[i].repl,
                  strlen(translit_table[i].repl));
}

static int multi_cmp(const void *a, const void *b)
{
    const MultiRule *x = a, *y = b;
    if (x->key_len != y->key_len) return x->key_len < y->key_len ? 1 : -1;
    return memcmp(x->key, y->key, x->key_len);
}

static void table_add_multi(Table *t, const unsigned char *key, size_t klen,
                            char *repl, size_t rlen)
{
    if (t->multi_n == t->multi_cap) {
        t->multi_cap = t->multi_cap ? t->multi_cap * 2 : 16;
        t->multi = xrealloc(t->multi, t->multi_cap * sizeof *t->multi);
    }
    MultiRule *m = &t->multi[t->multi_n++];
    memcpy(m->key, key, klen);
    m->key_len = klen;
    m->repl = repl;
    m->repl_len = rlen;
    t->multi_first[key[0]] = 1;
}

/* ------------------------------------------------------------ config file -- */

/*
 * Grammar (one rule per line):
 *
 *     KEY <whitespace> VALUE
 *
 * KEY is a run of non-whitespace bytes, interpreted as:
 *     U+2014 | u+2014 | 0x2014     a code point
 *     \xE2\x80\x94                 an explicit byte sequence
 *     =anything                    forced literal (drops the '=')
 *     anything else                literal UTF-8, exactly as pasted
 *
 * VALUE is the rest of the line. A '#' preceded by whitespace begins a
 * trailing comment. The remainder is trimmed. If it opens and closes with
 * a double quote the interior is taken exactly, with \\ \" \n \t \xHH
 * recognised. An empty VALUE is an error; write "" to delete a character.
 * A '#' as the first non-blank character makes the whole line a comment.
 */

static int parse_hex(const char *s, const char *e, uint32_t *out)
{
    uint32_t v = 0;
    if (s == e || (size_t)(e - s) > 6) return -1;
    for (; s < e; s++) {
        int d;
        if (*s >= '0' && *s <= '9') d = *s - '0';
        else if (*s >= 'a' && *s <= 'f') d = *s - 'a' + 10;
        else if (*s >= 'A' && *s <= 'F') d = *s - 'A' + 10;
        else return -1;
        v = v * 16 + (uint32_t)d;
    }
    if (v > 0x10FFFF) return -1;
    *out = v;
    return 0;
}

/* returns bytes written to out, or -1 */
static long key_to_bytes(const char *tok, size_t len, unsigned char *out,
                         size_t outcap, const char **why)
{
    uint32_t cp;

    if (len == 0) { *why = "empty key"; return -1; }

    if (tok[0] == '=') { tok++; len--; }                 /* forced literal */
    else if (len >= 3 && (tok[0] == 'U' || tok[0] == 'u') && tok[1] == '+') {
        if (parse_hex(tok + 2, tok + len, &cp) != 0) {
            *why = "bad U+ code point"; return -1;
        }
        return (long)utf8_encode(cp, out);
    }
    else if (len >= 3 && tok[0] == '0' && (tok[1] == 'x' || tok[1] == 'X')) {
        if (parse_hex(tok + 2, tok + len, &cp) != 0) {
            *why = "bad 0x code point"; return -1;
        }
        return (long)utf8_encode(cp, out);
    }
    else if (len >= 4 && tok[0] == '\\' && (tok[1] == 'x' || tok[1] == 'X')) {
        size_t n = 0, i = 0;
        while (i < len) {
            if (i + 4 > len || tok[i] != '\\' ||
                (tok[i + 1] != 'x' && tok[i + 1] != 'X')) {
                *why = "bad \\xHH byte sequence"; return -1;
            }
            if (parse_hex(tok + i + 2, tok + i + 4, &cp) != 0 || cp > 0xFF) {
                *why = "bad \\xHH byte sequence"; return -1;
            }
            if (n >= outcap) { *why = "key too long"; return -1; }
            out[n++] = (unsigned char)cp;
            i += 4;
        }
        return (long)n;
    }

    if (len > outcap) { *why = "key too long"; return -1; }
    memcpy(out, tok, len);
    return (long)len;
}

/* unescape a quoted VALUE in place; returns length or -1 */
static long unquote(const char *s, size_t len, char *out, size_t outcap,
                    const char **why)
{
    size_t n = 0, i = 0;
    while (i < len) {
        if (n >= outcap) { *why = "replacement too long"; return -1; }
        if (s[i] != '\\') { out[n++] = s[i++]; continue; }
        if (i + 1 >= len) { *why = "trailing backslash"; return -1; }
        switch (s[i + 1]) {
        case '\\': out[n++] = '\\'; i += 2; break;
        case '"':  out[n++] = '"';  i += 2; break;
        case 'n':  out[n++] = '\n'; i += 2; break;
        case 't':  out[n++] = '\t'; i += 2; break;
        case 'r':  out[n++] = '\r'; i += 2; break;
        case 'x': case 'X': {
            uint32_t v;
            if (i + 4 > len || parse_hex(s + i + 2, s + i + 4, &v) != 0) {
                *why = "bad \\xHH escape"; return -1;
            }
            out[n++] = (char)v;
            i += 4;
            break;
        }
        default: *why = "unknown escape"; return -1;
        }
    }
    return (long)n;
}

static void config_line(Table *t, char *line, const char *path, int lineno)
{
    char *p = line;
    const char *why = "";

    while (*p == ' ' || *p == '\t') p++;
    if (*p == '\0' || *p == '\n' || *p == '#') return;

    /* KEY */
    char *ks = p;
    while (*p && *p != ' ' && *p != '\t' && *p != '\n') p++;
    size_t klen = (size_t)(p - ks);

    /* separator */
    if (*p != ' ' && *p != '\t')
        fatal("%s:%d: no replacement (key and value are separated by "
              "whitespace)", path, lineno);
    while (*p == ' ' || *p == '\t') p++;

    /* VALUE: to end of line, minus a whitespace-preceded trailing comment */
    char *vs = p;
    char *ve = vs + strlen(vs);
    while (ve > vs && (ve[-1] == '\n' || ve[-1] == '\r')) ve--;
    for (char *q = vs; q < ve; q++) {
        if (*q == '#' && q > vs && (q[-1] == ' ' || q[-1] == '\t')) {
            ve = q;
            break;
        }
    }
    while (ve > vs && (ve[-1] == ' ' || ve[-1] == '\t')) ve--;
    size_t vlen = (size_t)(ve - vs);

    if (vlen == 0)
        fatal("%s:%d: empty replacement; write \"\" to delete the character",
              path, lineno);

    char rbuf[CFG_MAX_REPL];
    long rlen;
    if (vlen >= 2 && vs[0] == '"' && ve[-1] == '"') {
        rlen = unquote(vs + 1, vlen - 2, rbuf, sizeof rbuf, &why);
        if (rlen < 0) fatal("%s:%d: %s", path, lineno, why);
    } else {
        if (vlen >= sizeof rbuf)
            fatal("%s:%d: replacement too long", path, lineno);
        memcpy(rbuf, vs, vlen);
        rlen = (long)vlen;
    }

    unsigned char kbuf[CFG_MAX_KEY];
    long kb = key_to_bytes(ks, klen, kbuf, sizeof kbuf, &why);
    if (kb < 0) fatal("%s:%d: %s", path, lineno, why);

    char *repl = xstrndup(rbuf, (size_t)rlen);

    /* one code point -> hash; more than one -> longest-match list */
    uint32_t cp;
    size_t used = utf8_decode(kbuf, kbuf + kb, &cp);
    if (used == (size_t)kb && used > 0)
        table_set(t, cp, repl, (size_t)rlen);
    else
        table_add_multi(t, kbuf, (size_t)kb, repl, (size_t)rlen);
}

static int config_load(Table *t, const char *path, int required)
{
    FILE *f = fopen(path, "r");
    if (!f) {
        if (required) fatal("%s: %s", path, strerror(errno));
        return 0;
    }
    char line[4096];
    int lineno = 0;
    while (fgets(line, sizeof line, f)) {
        lineno++;
        if (!strchr(line, '\n') && !feof(f)) {
            fclose(f);
            fatal("%s:%d: line exceeds %zu bytes", path, lineno,
                  sizeof line - 1);
        }
        config_line(t, line, path, lineno);
    }
    if (ferror(f)) { fclose(f); fatal("%s: read error", path); }
    fclose(f);
    if (opt_verbose) warnx_("config: %s", path);
    return 1;
}

static void config_discover(Table *t, const char *explicit_path)
{
    if (explicit_path) { config_load(t, explicit_path, 1); return; }

    const char *env = getenv("ASCIIXLATE_CONFIG");
    if (env && *env) { config_load(t, env, 1); return; }

    const char *home = getenv("HOME");
    if (home && *home) {
        size_t n = strlen(home) + sizeof "/.asciixlate";
        char *p = xmalloc(n);
        snprintf(p, n, "%s/.asciixlate", home);
        config_load(t, p, 0);
        free(p);
    }
}

/* ---------------------------------------------------------------- census -- */

static void census_note(uint32_t cp)
{
    for (size_t i = 0; i < census_n; i++)
        if (census[i].cp == cp) { census[i].n++; return; }
    if (census_n == census_cap) {
        census_cap = census_cap ? census_cap * 2 : 64;
        census = xrealloc(census, census_cap * sizeof *census);
    }
    census[census_n].cp = cp;
    census[census_n].n = 1;
    census_n++;
}

static int census_cmp(const void *a, const void *b)
{
    const Census *x = a, *y = b;
    if (x->n != y->n) return x->n < y->n ? 1 : -1;
    return x->cp < y->cp ? -1 : x->cp > y->cp;
}

static void census_print(void)
{
    if (census_n == 0) {
        printf("# every character had a mapping; nothing to report\n");
        return;
    }
    qsort(census, census_n, sizeof *census, census_cmp);
    printf("# asciixlate --report: unmapped code points, most frequent first.\n"
           "# Edit the replacements and append to ~/.asciixlate\n");
    for (size_t i = 0; i < census_n; i++) {
        unsigned char u[4];
        size_t n = utf8_encode(census[i].cp, u);
        printf("U+%04X\t%s\t# %zu occurrence%s, bytes",
               census[i].cp, DEFAULT_MARKER, census[i].n,
               census[i].n == 1 ? "" : "s");
        for (size_t j = 0; j < n; j++) printf(" %02X", u[j]);
        putchar('\n');
    }
}

/* ------------------------------------------------------------- conversion -- */

typedef struct { char *p; size_t n, cap; } Buf;

static void buf_init(Buf *b, size_t cap)
{
    b->p = xmalloc(cap);
    b->n = 0;
    b->cap = cap;
}

static void buf_put(Buf *b, const void *src, size_t n)
{
    if (b->n + n > b->cap) {
        while (b->n + n > b->cap) {
            if (b->cap > (size_t)-1 / 2) fatal("output too large");
            b->cap *= 2;
        }
        b->p = xrealloc(b->p, b->cap);
    }
    memcpy(b->p + b->n, src, n);
    b->n += n;
}

static void convert(const Table *t, const unsigned char *in, size_t len,
                    Buf *out, Stats *st)
{
    const unsigned char *p = in, *end = in + len;

    while (p < end) {
        /* multi-code-point rules, longest first */
        if (t->multi_n && t->multi_first[*p]) {
            size_t i;
            for (i = 0; i < t->multi_n; i++) {
                const MultiRule *m = &t->multi[i];
                if ((size_t)(end - p) >= m->key_len &&
                    memcmp(p, m->key, m->key_len) == 0) {
                    buf_put(out, m->repl, m->repl_len);
                    p += m->key_len;
                    st->replaced++;
                    break;
                }
            }
            if (i < t->multi_n) continue;
        }

        /* plain ASCII with no override: the common case */
        if (*p < 0x80 && !t->ascii_mapped[*p]) {
            const unsigned char *run = p;
            while (p < end && *p < 0x80 && !t->ascii_mapped[*p]) p++;
            buf_put(out, run, (size_t)(p - run));
            continue;
        }

        uint32_t cp;
        size_t used = utf8_decode(p, end, &cp);
        if (used == 0) {                        /* malformed byte */
            st->invalid++;
            if (opt_keep) buf_put(out, p, 1);
            else buf_put(out, marker, marker_len);
            p++;
            continue;
        }

        const Slot *s = table_get(t, cp);
        if (s) {
            buf_put(out, s->repl, s->len);
            st->replaced++;
            p += used;
            continue;
        }

        if (cp < 0x80) {                        /* unmapped ASCII: verbatim */
            buf_put(out, p, 1);
            p += used;
            continue;
        }

        st->unmapped++;
        if (opt_report) census_note(cp);
        if (opt_keep) buf_put(out, p, used);
        else buf_put(out, marker, marker_len);
        p += used;
    }
}

/* ---------------------------------------------------------------- file io -- */

/* returns 0 ok, -1 refused (message already printed) */
static int slurp(const char *path, unsigned char **buf, size_t *len,
                 mode_t *mode)
{
    int fd = open(path, O_RDONLY);
    if (fd < 0) { warnx_("%s: cannot process (%s)", path, strerror(errno)); return -1; }

    struct stat sb;
    if (fstat(fd, &sb) != 0) {
        warnx_("%s: cannot process (%s)", path, strerror(errno));
        close(fd);
        return -1;
    }
    if (!S_ISREG(sb.st_mode)) {
        warnx_("%s: cannot process (not a regular file)", path);
        close(fd);
        return -1;
    }
    if ((unsigned long long)sb.st_size > (unsigned long long)opt_max_size) {
        warnx_("%s: cannot process (%llu bytes exceeds limit %lu; raise with "
               "--max-size)", path, (unsigned long long)sb.st_size,
               opt_max_size);
        close(fd);
        return -1;
    }

    size_t n = (size_t)sb.st_size;
    unsigned char *b = xmalloc(n + 1);
    size_t got = 0;
    while (got < n) {
        ssize_t r = read(fd, b + got, n - got);
        if (r < 0) {
            if (errno == EINTR) continue;
            warnx_("%s: cannot process (%s)", path, strerror(errno));
            free(b);
            close(fd);
            return -1;
        }
        if (r == 0) break;
        got += (size_t)r;
    }
    close(fd);
    b[got] = '\0';

    if (!opt_allow_binary) {
        size_t sniff = got < BINARY_SNIFF ? got : BINARY_SNIFF;
        if (memchr(b, '\0', sniff)) {
            warnx_("%s: cannot process (binary: NUL byte in first %zu bytes; "
                   "override with --allow-binary)", path, sniff);
            free(b);
            return -1;
        }
    }

    *buf = b;
    *len = got;
    *mode = sb.st_mode & 07777;
    return 0;
}

/* atomic replace: write a sibling temp file, fsync, rename */
static int write_atomic(const char *path, const char *data, size_t len,
                        mode_t mode)
{
    size_t dlen = strlen(path);
    char *tmp = xmalloc(dlen + sizeof ".asciixlate.XXXXXX");
    const char *slash = strrchr(path, '/');
    if (slash) {
        size_t dir = (size_t)(slash - path) + 1;
        memcpy(tmp, path, dir);
        snprintf(tmp + dir, dlen + sizeof ".asciixlate.XXXXXX" - dir,
                 ".asciixlate.XXXXXX");
    } else {
        snprintf(tmp, dlen + sizeof ".asciixlate.XXXXXX",
                 ".asciixlate.XXXXXX");
    }

    int fd = mkstemp(tmp);
    if (fd < 0) { warnx_("%s: %s", tmp, strerror(errno)); free(tmp); return -1; }

    size_t off = 0;
    while (off < len) {
        ssize_t w = write(fd, data + off, len - off);
        if (w < 0) {
            if (errno == EINTR) continue;
            warnx_("%s: write failed (%s)", tmp, strerror(errno));
            close(fd); unlink(tmp); free(tmp);
            return -1;
        }
        off += (size_t)w;
    }
    if (fchmod(fd, mode) != 0 && opt_verbose)
        warnx_("%s: fchmod: %s", tmp, strerror(errno));
    if (fsync(fd) != 0) {
        warnx_("%s: fsync failed (%s)", tmp, strerror(errno));
        close(fd); unlink(tmp); free(tmp);
        return -1;
    }
    if (close(fd) != 0) {
        warnx_("%s: close failed (%s)", tmp, strerror(errno));
        unlink(tmp); free(tmp);
        return -1;
    }
    if (rename(tmp, path) != 0) {
        warnx_("%s: rename failed (%s)", path, strerror(errno));
        unlink(tmp); free(tmp);
        return -1;
    }
    free(tmp);
    return 0;
}

/*
 * Write to a named output. A path that already exists and is not a regular
 * file (a device, a fifo) is written through directly --- replacing such a
 * target by rename would destroy the node. Everything else is replaced
 * atomically.
 */
static int write_out(const char *path, const char *data, size_t len,
                     mode_t mode)
{
    struct stat sb;
    if (stat(path, &sb) == 0 && !S_ISREG(sb.st_mode)) {
        int fd = open(path, O_WRONLY);
        if (fd < 0) { warnx_("%s: %s", path, strerror(errno)); return -1; }
        size_t off = 0;
        while (off < len) {
            ssize_t w = write(fd, data + off, len - off);
            if (w < 0) {
                if (errno == EINTR) continue;
                warnx_("%s: write failed (%s)", path, strerror(errno));
                close(fd);
                return -1;
            }
            off += (size_t)w;
        }
        if (close(fd) != 0) {
            warnx_("%s: close failed (%s)", path, strerror(errno));
            return -1;
        }
        return 0;
    }
    return write_atomic(path, data, len, mode);
}

static int write_stdout(const char *data, size_t len)
{
    if (len && fwrite(data, 1, len, stdout) != len) {
        warnx_("stdout: write failed (%s)", strerror(errno));
        return -1;
    }
    if (fflush(stdout) != 0) {
        warnx_("stdout: write failed (%s)", strerror(errno));
        return -1;
    }
    return 0;
}

/* --------------------------------------------------------------- listing -- */

static void print_escaped(const char *s, size_t n)
{
    for (size_t i = 0; i < n; i++) {
        unsigned char c = (unsigned char)s[i];
        if (c == '\\') fputs("\\\\", stdout);
        else if (c == '"') fputs("\\\"", stdout);
        else if (c == '\n') fputs("\\n", stdout);
        else if (c == '\t') fputs("\\t", stdout);
        else if (c >= 0x20 && c < 0x7F) putchar((int)c);
        else printf("\\x%02X", c);
    }
}

static int list_cmp(const void *a, const void *b)
{
    const Slot *x = a, *y = b;
    return x->cp < y->cp ? -1 : x->cp > y->cp;
}

static void table_list(const Table *t)
{
    Slot *v = xmalloc((t->mask + 1) * sizeof *v);
    size_t n = 0;
    for (size_t i = 0; i <= t->mask; i++)
        if (t->slot[i].used) v[n++] = t->slot[i];
    qsort(v, n, sizeof *v, list_cmp);

    printf("# %zu single-code-point rules, %zu multi-code-point rules\n",
           n, t->multi_n);
    for (size_t i = 0; i < n; i++) {
        printf("U+%04X\t\"", v[i].cp);
        print_escaped(v[i].repl, v[i].len);
        printf("\"\n");
    }
    for (size_t i = 0; i < t->multi_n; i++) {
        const MultiRule *m = &t->multi[i];
        fputs("\\x", stdout);
        for (size_t j = 0; j < m->key_len; j++)
            printf("%s%02X", j ? "\\x" : "", (unsigned char)m->key[j]);
        printf("\t\"");
        print_escaped(m->repl, m->repl_len);
        printf("\"\n");
    }
    free(v);
}

/* ------------------------------------------------------------ help / man -- */

static const char usage_text[] =
PROG " " VERSION " --- UTF-8 to ASCII transliteration with a local rule file\n"
"\n"
"usage: " PROG " [options] FILE...\n"
"\n"
"  -i, --in-place       rewrite each FILE in place (temp file plus rename)\n"
"  -o, --output FILE    write to FILE; one input only\n"
"  -c, --config FILE    rule file (default: $ASCIIXLATE_CONFIG or ~/.asciixlate)\n"
"  -r, --report         print rule stubs for unmapped code points; write nothing\n"
"  -n, --dry-run        convert and count, write nothing\n"
"  -l, --list           print the active rule table and exit\n"
"  -k, --keep           emit the original UTF-8 for unmapped characters\n"
"  -m, --marker STR     text for unmapped characters (default \"" DEFAULT_MARKER "\")\n"
"  -s, --strict         exit 2 if any character was unmapped\n"
"  -M, --max-size SIZE  refuse files above SIZE (default 64M; K/M/G accepted)\n"
"  -B, --allow-binary   do not refuse files containing NUL\n"
"      --no-defaults    start from an empty table; use only the rule file\n"
"  -v, --verbose        per-file summary on stderr\n"
"  -q, --quiet          suppress the summary\n"
"  -h, --usage          this message\n"
"      --help           the full manual\n"
"      --version        version\n"
"\n"
"With no -i and no -o, converted text goes to standard output.\n"
"Standard input is not read; " PROG " operates on named regular files.\n"
"Run '" PROG " --help' for the full manual.\n";

static const char manual_0[] =
"NAME\n"
"    " PROG " --- transliterate UTF-8 text to ASCII under local rules\n"
"\n"
"SYNOPSIS\n"
"    " PROG " [-i | -o FILE] [-c FILE] [-krsnl] [-m STR] [-M SIZE] FILE...\n"
"    " PROG " -h | --help | --version\n"
"\n"
"DESCRIPTION\n"
"    " PROG " reads UTF-8 text files and writes ASCII. Each code point is\n"
"    resolved in this order:\n"
"\n"
"      1. a multi-code-point rule from the rule file, longest match first\n"
"      2. a single-code-point rule from the rule file\n"
"      3. the built-in transliteration table\n"
"      4. otherwise the character is unmapped: the marker is emitted\n"
"\n"
"    The built-in table is compiled into the binary. There is no libiconv,\n"
"    no gconv, and no runtime data file, so a given input yields identical\n"
"    output on Darwin, Linux and NetBSD, and on a host with no locale data.\n"
"\n"
"    Input is decoded as UTF-8. A malformed byte is counted as invalid and\n"
"    replaced with the marker, or kept as-is under -k.\n"
"\n"
"RULE FILE\n"
"    One rule per line:\n"
"\n"
"        KEY <whitespace> VALUE\n"
"\n"
"    A line whose first non-blank character is '#' is a comment. Blank\n"
"    lines are ignored.\n"
"\n"
"    KEY is a run of non-whitespace bytes, read as:\n"
"\n"
"        U+2014          a code point, four to six hex digits\n"
"        0x2014          the same\n"
"        \\xE2\\x80\\x94     an explicit byte sequence\n"
"        =U+2014         forced literal: the six characters U, +, 2, 0, 1, 4\n"
"        anything else   literal UTF-8, exactly as pasted\n"
"\n"
"    The literal form is the point of the format. Yank an unfamiliar\n"
"    character out of a vim buffer, put it at the start of a line, type a\n"
"    tab and its replacement, and the rule is written. A literal key of\n"
"    more than one code point becomes a longest-match rule, so a two-\n"
"    character sequence can be replaced as a unit.\n"
"\n"
"    VALUE is the rest of the line. A '#' preceded by whitespace begins a\n"
"    trailing comment; the remainder is trimmed. If VALUE opens and closes\n"
"    with a double quote, the interior is taken exactly, and \\\\ \\\" \\n \\t\n"
"    \\r and \\xHH are recognised. Quoting is how a replacement holds\n"
"    leading or trailing spaces, a '#', or nothing at all.\n"
"\n"
"    An unquoted empty VALUE is an error, not a deletion. To delete a\n"
"    character, write the empty string explicitly:\n"
"\n"
"        U+00AD  \"\"              # soft hyphen: drop it\n"
"        U+00A0  \" \"             # no-break space: one plain space\n"
"        U+2014  ---             # em dash: three hyphens\n"
"        U+2026  ...             # ellipsis\n"
"        \\xC2\\xA9  (c)             # copyright sign, by byte sequence\n"
"        ffi     ffi             # a pasted ligature, spelled out\n"
"\n"
"    Rules override the built-in table for the same key. --no-defaults\n"
"    discards the built-in table and uses the rule file alone.\n"
"\n"
"RULE FILE DISCOVERY\n"
"    -c FILE if given, else $ASCIIXLATE_CONFIG if set, else ~/.asciixlate.\n"
"    A named file that cannot be read is an error. A missing ~/.asciixlate\n"
"    is not.\n"
"\n"
"BUILDING A RULE FILE\n"
"    --report converts without writing and prints a ready-to-edit stub for\n"
"    every unmapped code point, most frequent first:\n"
"\n"
"        " PROG " --report page.md >> ~/.asciixlate\n"
"\n"
"    Edit the replacements in place and the next run is clean. --list\n";

static const char manual_1[] =
"    prints the whole active table in the same grammar, so the built-in\n"
"    defaults can be captured, edited and pinned.\n"
"\n"
"REFUSALS\n"
"    " PROG " declines rather than guesses. A file is refused, with a\n"
"    message naming the reason, when it is not a regular file, when it\n"
"    exceeds --max-size, or when a NUL byte appears in its first 8192\n"
"    bytes. Refusals do not stop the remaining files; the exit status\n"
"    records that something was refused.\n"
"\n"
"OUTPUT\n"
"    Without -i or -o, converted text goes to standard output and multiple\n"
"    inputs are concatenated. With -o, output goes to that file; only one\n"
"    input is permitted. With -i, each file is rewritten.\n"
"\n"
"    File output is atomic: a temporary sibling is written, flushed with\n"
"    fsync, given the original file's mode, and renamed over the target.\n"
"    An interrupted or failed run leaves the original intact. Every write,\n"
"    flush and close is checked; " PROG " never exits 0 having lost bytes.\n"
"\n"
"EXIT STATUS\n"
"    0   every file converted\n"
"    1   usage error, rule file error, or a file was refused or failed\n"
"    2   --strict was given and at least one character was unmapped\n"
"\n"
"ENVIRONMENT\n"
"    ASCIIXLATE_CONFIG   rule file path, consulted when -c is absent\n"
"    HOME                locates ~/.asciixlate\n"
"\n"
"EXAMPLES\n"
"    " PROG " notes.md > notes.ascii.md\n"
"    " PROG " -i *.md\n"
"    " PROG " --report archive/*.md >> ~/.asciixlate\n"
"    " PROG " -s -n draft.md            # fail if anything is unmapped\n"
"    " PROG " -k -m '' page.md          # keep unmapped characters as UTF-8\n"
"\n"
"HELP\n"
"    -h prints a one-screen summary of the options. --help prints this\n"
"    manual, which is the same text the installed man page carries;\n"
"    --manual is an accepted alias. Both are compiled into the binary,\n"
"    so there is nothing to install and nothing to drift.\n"
"\n"
"AUTHOR\n"
"    George Georgalis <george@iuxta.com>\n";

static const char *const manual_parts[] = { manual_0, manual_1 };

#define MANUAL_PARTS (sizeof manual_parts / sizeof manual_parts[0])

/* ------------------------------------------------------------------ main -- */

static unsigned long parse_size(const char *s)
{
    char *e;
    errno = 0;
    unsigned long v = strtoul(s, &e, 10);
    if (errno || e == s) fatal("bad size: %s", s);
    if (*e == 'k' || *e == 'K') { v *= 1024UL; e++; }
    else if (*e == 'm' || *e == 'M') { v *= 1024UL * 1024UL; e++; }
    else if (*e == 'g' || *e == 'G') { v *= 1024UL * 1024UL * 1024UL; e++; }
    if (*e) fatal("bad size: %s", s);
    return v;
}

int main(int argc, char **argv)
{
    const char *config = NULL;
    int no_defaults = 0, list_only = 0;
    int i, end_opts = 0;

    for (i = 1; i < argc; i++) {
        const char *a = argv[i];
        if (!end_opts && !strcmp(a, "--")) { end_opts = 1; continue; }
        if (end_opts || a[0] != '-' || a[1] == '\0') break;

        if (!strcmp(a, "-h") || !strcmp(a, "--usage")) {
            fputs(usage_text, stdout);
            return 0;
        }
        if (!strcmp(a, "--help") || !strcmp(a, "--manual")) {
            for (size_t k = 0; k < MANUAL_PARTS; k++)
                fputs(manual_parts[k], stdout);
            return 0;
        }
        if (!strcmp(a, "--version")) { printf("%s %s\n", PROG, VERSION); return 0; }
        if (!strcmp(a, "-v") || !strcmp(a, "--verbose")) { opt_verbose = 1; continue; }
        if (!strcmp(a, "-q") || !strcmp(a, "--quiet")) { opt_quiet = 1; continue; }
        if (!strcmp(a, "-i") || !strcmp(a, "--in-place")) { opt_inplace = 1; continue; }
        if (!strcmp(a, "-n") || !strcmp(a, "--dry-run")) { opt_dryrun = 1; continue; }
        if (!strcmp(a, "-r") || !strcmp(a, "--report")) { opt_report = 1; continue; }
        if (!strcmp(a, "-l") || !strcmp(a, "--list")) { list_only = 1; continue; }
        if (!strcmp(a, "-k") || !strcmp(a, "--keep")) { opt_keep = 1; continue; }
        if (!strcmp(a, "-s") || !strcmp(a, "--strict")) { opt_strict = 1; continue; }
        if (!strcmp(a, "-B") || !strcmp(a, "--allow-binary")) { opt_allow_binary = 1; continue; }
        if (!strcmp(a, "--no-defaults")) { no_defaults = 1; continue; }

        if (!strcmp(a, "-c") || !strcmp(a, "--config")) {
            if (++i >= argc) fatal("%s requires a file", a);
            config = argv[i];
            continue;
        }
        if (!strcmp(a, "-o") || !strcmp(a, "--output")) {
            if (++i >= argc) fatal("%s requires a file", a);
            opt_output = argv[i];
            continue;
        }
        if (!strcmp(a, "-m") || !strcmp(a, "--marker")) {
            if (++i >= argc) fatal("%s requires a string", a);
            marker = argv[i];
            marker_len = strlen(marker);
            continue;
        }
        if (!strcmp(a, "-M") || !strcmp(a, "--max-size")) {
            if (++i >= argc) fatal("%s requires a size", a);
            opt_max_size = parse_size(argv[i]);
            continue;
        }
        fatal("unknown option: %s (try -h)", a);
    }

    if (opt_inplace && opt_output) fatal("-i and -o are mutually exclusive");
    if (opt_output && argc - i > 1) fatal("-o takes exactly one input file");

    Table t;
    table_init(&t, TRANSLIT_TABLE_N + 256);
    if (!no_defaults) table_load_defaults(&t);
    config_discover(&t, config);
    if (t.multi_n > 1) qsort(t.multi, t.multi_n, sizeof *t.multi, multi_cmp);

    if (list_only) { table_list(&t); return 0; }

    if (i >= argc)
        fatal("no input files (standard input is not read; try -h)");

    int status = EX_OK;
    Stats total = {0, 0, 0, 0, 0};

    for (; i < argc; i++) {
        const char *path = argv[i];
        unsigned char *in = NULL;
        size_t len = 0;
        mode_t mode = 0644;

        if (slurp(path, &in, &len, &mode) != 0) {
            if (status == EX_OK) status = EX_USAGE;
            continue;
        }

        Buf out;
        buf_init(&out, len + len / 8 + 64);
        Stats st = {0, 0, 0, 0, 0};
        convert(&t, in, len, &out, &st);
        st.bytes_in = len;
        st.bytes_out = out.n;
        free(in);

        if (!opt_dryrun && !opt_report) {
            int rc;
            if (opt_inplace) rc = write_atomic(path, out.p, out.n, mode);
            else if (opt_output) rc = write_out(opt_output, out.p, out.n, 0644);
            else rc = write_stdout(out.p, out.n);
            if (rc != 0) status = EX_USAGE;
        }
        free(out.p);

        total.bytes_in += st.bytes_in;
        total.bytes_out += st.bytes_out;
        total.replaced += st.replaced;
        total.unmapped += st.unmapped;
        total.invalid += st.invalid;

        if (opt_verbose)
            warnx_("%s: %zu -> %zu bytes, %zu replaced, %zu unmapped, "
                   "%zu invalid", path, st.bytes_in, st.bytes_out,
                   st.replaced, st.unmapped, st.invalid);
    }

    if (opt_report) census_print();

    if (!opt_quiet && !opt_verbose && !opt_report &&
        (total.unmapped || total.invalid))
        warnx_("%zu unmapped, %zu invalid (--report lists them)",
               total.unmapped, total.invalid);

    if (opt_strict && (total.unmapped || total.invalid) && status == EX_OK)
        status = EX_UNMAPPED;

    return status;
}
