#!/usr/bin/env python3
"""
mktable.py --- generate translit_table.h for asciixlate.

Provenance of every entry, in precedence order (later wins):

  1. NFKD folding      Unicode compatibility decomposition with combining
                       marks stripped; ASCII-only results kept.
  2. iconv seeding     glibc "ascii//TRANSLIT" output, for code points NFKD
                       leaves undecomposed (ligatures, currency, symbols).
                       Captured once, at generation time, and pinned into
                       the C source --- the built binary never calls iconv.
  3. CURATED           hand-set entries below. These are the deliberate
                       divergences from glibc, and the reason this file
                       exists rather than a runtime iconv call.

Run under any Python 3 with a glibc iconv(1) available. The output is
deterministic for a given Python/Unicode version; regenerate and diff to
audit a Unicode upgrade.
"""
import unicodedata as ud, subprocess, sys, datetime

RANGES = [
 (0x00A0,0x024F),(0x0250,0x02AF),(0x02B0,0x02FF),(0x0300,0x036F),
 (0x1E00,0x1EFF),(0x2000,0x206F),(0x2070,0x209F),(0x20A0,0x20BF),
 (0x2100,0x214F),(0x2150,0x218F),(0x2190,0x21FF),(0x2200,0x22FF),
 (0x2300,0x23FF),(0x2400,0x243F),(0x2440,0x245F),(0x2460,0x24FF),
 (0x2500,0x257F),(0x2580,0x259F),(0x25A0,0x25FF),(0x2600,0x26FF),
 (0x2700,0x27BF),(0x27C0,0x27EF),(0x27F0,0x27FF),(0x2900,0x297F),
 (0x2980,0x29FF),(0x2A00,0x2AFF),(0x2E00,0x2E7F),(0x3000,0x303F),
 (0xFB00,0xFB4F),(0xFE10,0xFE1F),(0xFE30,0xFE4F),(0xFE50,0xFE6F),
 (0xFF00,0xFFEF),
]

# ---- 3. CURATED -----------------------------------------------------------
# Every line here is a decision, not a derivation. Keep it short; anything
# a user might reasonably disagree with belongs in ~/.asciixlate, not here.
CURATED = {
    # dashes --- the whole reason the tool exists
    0x2010:"-",    0x2011:"-",    0x2012:"-",
    0x2013:"--",   0x2014:"---",  0x2015:"--",
    0x2E3A:"----", 0x2E3B:"-----",
    0x2212:"-",                       # MINUS SIGN
    0x00AD:"",                        # SOFT HYPHEN: drop (glibc emits "-")
    # quotes
    0x2018:"'", 0x2019:"'", 0x201A:"'", 0x201B:"'",
    0x201C:'"', 0x201D:'"', 0x201E:'"', 0x201F:'"',
    0x2032:"'", 0x2033:'"', 0x2035:"'", 0x2036:'"',
    0x00AB:'"', 0x00BB:'"',           # guillemets (glibc: << >>)
    0x2039:"'", 0x203A:"'",
    # spaces and invisibles
    0x00A0:" ", 0x2007:" ", 0x202F:" ", 0x205F:" ", 0x3000:" ",
    0x200B:"", 0x200C:"", 0x200D:"", 0x2060:"", 0xFEFF:"",
    0x200E:"", 0x200F:"", 0x061C:"",
    # markdown-relevant punctuation
    0x2022:"*", 0x2023:"*", 0x2043:"-", 0x25E6:"*", 0x2219:"*",
    0x2026:"...", 0x2027:".",
    0x00B7:".",  0x2024:".",
    # arrows (glibc yields "?" for most)
    0x2190:"<-", 0x2192:"->", 0x2194:"<->",
    0x21D0:"<=", 0x21D2:"=>", 0x21D4:"<=>",
    0x2191:"^",  0x2193:"v",
    # symbols worth keeping legible
    0x00A9:"(c)", 0x00AE:"(r)", 0x2122:"(tm)", 0x2117:"(p)",
    0x2713:"[x]", 0x2714:"[x]", 0x2717:"[ ]", 0x2718:"[ ]",
    0x00B0:" deg", 0x00B1:"+/-", 0x00D7:"x", 0x00F7:"/",
    0x2260:"!=", 0x2264:"<=", 0x2265:">=", 0x2248:"~",
    0x00A6:"|", 0x00AC:"~",
}
# ---------------------------------------------------------------------------

def nfkd_fold(cp):
    ch = chr(cp)
    if ud.category(ch) == 'Mn':
        return ''
    d = ud.normalize('NFKD', ch)
    out = ''.join(c for c in d if ud.category(c) != 'Mn')
    if out != ch and out and all(ord(c) < 0x80 for c in out):
        return out
    return None

def main():
    cps = []
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            try: ud.name(chr(cp))
            except ValueError: continue
            cps.append(cp)

    table, prov = {}, {}
    for cp in cps:
        f = nfkd_fold(cp)
        if f is not None:
            table[cp], prov[cp] = f, 'nfkd'

    missing = [cp for cp in cps if cp not in table]
    src = "\n".join(chr(c) for c in missing) + "\n"
    p = subprocess.run(['iconv', '-f', 'utf-8', '-t', 'ascii//TRANSLIT'],
                       input=src.encode(), capture_output=True)
    if p.returncode != 0:
        sys.exit("iconv seeding failed: " + p.stderr.decode()[:200])
    lines = p.stdout.decode('ascii', 'replace').split("\n")
    for i, cp in enumerate(missing):
        if i >= len(lines): break
        o = lines[i]
        if o and '?' not in o and all(0x20 <= ord(c) < 0x7F for c in o):
            table[cp], prov[cp] = o, 'iconv'

    for cp, v in CURATED.items():
        table[cp], prov[cp] = v, 'curated'

    n = {'nfkd':0, 'iconv':0, 'curated':0}
    for cp in table: n[prov[cp]] += 1

    def cesc(s):
        return ''.join('\\"' if c == '"' else '\\\\' if c == '\\' else c for c in s)

    keys = sorted(table)
    with open('translit_table.h', 'w') as f:
        f.write("/* Generated by mktable.py --- do not edit by hand.\n")
        f.write(" * Unicode %s, generated %s\n" % (ud.unidata_version,
                datetime.date.today().isoformat()))
        f.write(" * entries: %d (nfkd %d, iconv-seeded %d, curated %d)\n"
                % (len(table), n['nfkd'], n['iconv'], n['curated']))
        f.write(" */\n#ifndef ASCIIXLATE_TRANSLIT_TABLE_H\n"
                "#define ASCIIXLATE_TRANSLIT_TABLE_H\n\n"
                "typedef struct { unsigned int cp; const char *repl; } TranslitEntry;\n\n"
                "static const TranslitEntry translit_table[] = {\n")
        for cp in keys:
            try: nm = ud.name(chr(cp))
            except ValueError: nm = ""
            f.write('    {0x%04X, "%s"},%s/* %-7s %s */\n'
                    % (cp, cesc(table[cp]),
                       ' ' * max(1, 18 - len(cesc(table[cp]))),
                       prov[cp], nm[:44]))
        f.write("};\n\n#define TRANSLIT_TABLE_N "
                "(sizeof translit_table / sizeof translit_table[0])\n"
                "#define TRANSLIT_MAX_REPL %d\n\n#endif\n"
                % max(len(v) for v in table.values()))

    print("entries: %d  (nfkd %d, iconv %d, curated %d)"
          % (len(table), n['nfkd'], n['iconv'], n['curated']))
    print("max replacement: %d bytes" % max(len(v) for v in table.values()))
    print("unmapped in scanned ranges (-> ??): %d" % (len(cps) - len(table)))

main()
