#!/bin/sh

# REQUIRE: shell
# BEFORE: 
# PROVIDE: skel
# KEYWORD: ubt

set -e 

[ -e ../../dot-skel -a -e ../../mkinst/skel-inst.sh ] \
	&& sh ../../mkinst/skel-inst.sh ../../dot-skel /etc/skel \
	&& sh ../../mkinst/skel-inst.sh ../../dot-skel 

