#!/bin/sh

# REQUIRE:
# BEFORE:
# PROVIDE: time
# KEYWORD: cos7-boot

# set the clock and turn on ntp before touching any other file

set -e

yum -y install ntpdate
# cannot lookup north-america.pool.ntp.org before dnscache...
ntpdate 152.2.21.1 || true
systemctl enable ntpdate
yum -y install ntp
# configure /etc/ntp.conf to use
# server          north-america.pool.ntp.org
systemctl start ntpd
systemctl enable ntpd
# systemctl status ntpd

# benchmark the install time
mkdir -p /var/cfmake/ \
	&& touch /var/cfmake/nulltime \
	&& chmod 0 /var/cfmake/nulltime

	#&& touch -d "$(date -d yesterday '+%D 00:00:00')" \
	#	/var/cfmake/nulltime \

