#!/bin/sh

# REQUIRE: pkgin
# BEFORE:
# PROVIDE: certs
# KEYWORD: nbsd

set -e 

stderr () { echo ">>> $* <<<" 1>&2 ;} #:> return args to stderr
chkerr () { [ "$*" ] && { stderr "$*" ; return 1 ;} || true ;}

pkgin -y install mozilla-rootcerts
touch /etc/openssl/openssl.cnf
{ set -x ; mozilla-rootcerts install 2>&1 ;} | while read l ; do printf '.' ; done 
echo

exit 0

