#!/bin/sh

# REQUIRE:
# BEFORE: shell
# PROVIDE: etc
# KEYWORD: nbsd


set -e

#:: Symlink /home to /usr/home, if necessary.
#[ ! -e /home ] && mkdir /usr/home && ln -s usr/home /home || true

# hostname per dhcp
HOSTNAME=$(hostname)
echo "hostname=$HOSTNAME" >>/etc/rc.conf
sed "/localhost/s/$/ $HOSTNAME/" /etc/hosts >/etc/hosts~ && mv /etc/hosts~ /etc/hosts

#:: Stop inetd, permanently.
#/etc/rc.d/inetd stop || true
echo "inetd=no" >>/etc/rc.conf

# #:: Determine interface to use to network configuration.
# echo ; for n in `ifconfig -l | sed 's/lo0//'` ; do printf "$n $(ifconfig $n | grep -E 'media: |status: |inet ')\n\n"; done
# while [ -z "$dhcp_interface" ] ; do
#  read -p "Enter an interface for DHCP: [$(ifconfig -l | sed 's/lo0//' | cut -b-72)] " dhcp_interface
# done
# #:: Create configuration files to start networking at boot.
# echo "dhclient=NO" >>/etc/rc.conf
# cat >/etc/ifconfig.$dhcp_interface <<'EOF'
# up
# !dhclient $int
# #22.33.44.50 netmask 255.255.255.240
# #22.33.44.51 netmask 255.255.255.240 alias
# #!route add default 22.33.44.1
# EOF
# # Re-start networking using new config files.
# [ -e /var/run/dhclient.pid ] && dhclient -r
# /etc/rc.d/network stop
# /etc/rc.d/network start


chmod 700 /root /etc/skel

exit 0
