#!/bin/sh

# REQUIRE: shell
# BEFORE:
# PROVIDE: pkgin
# KEYWORD: nbsd

set -e 

chkerr () { [ -n "$*" ] && echo "ERR  >>->-- $0: $* --<-<< " >&2 && exit 1 ;}

URLROOT="http://ftp.netbsd.org/pub/"
PKG_PATH="${URLROOT}/pkgsrc/packages/NetBSD/$(uname -m)/$(uname -r|cut -f 1-2 -d .| cut -f 1 -d _)/All"
PKG_PATH="${URLROOT}/pkgsrc/packages/NetBSD/$(uname -m)/$(uname -r|cut -f 1 -d _)/All"
PKG_PATH="${URLROOT}/pkgsrc/packages/NetBSD/7.0.2/All"
PKG_PATH="http://ftp.netbsd.org/pub//pkgsrc/packages/NetBSD/amd64/7.0.2/All"
PKGIN_CONF="/usr/pkg/etc/pkgin/repositories.conf"

	pkg_add ${PKG_PATH}/pkgin
	[ $? -eq 0 ] || chkerr "pkgin setup failed"
	sed -e 's/^[^#].*$/#&/' ${PKGIN_CONF} > ${PKGIN_CONF}.new
	echo $PKG_PATH >> ${PKGIN_CONF}.new
	mv ${PKGIN_CONF}.new ${PKGIN_CONF}
	/usr/pkg/bin/pkgin -y update

#pkgin -y upgrade
#pkgin -y full-upgrade

cd $(dirname $0)
t="$(mktemp /tmp/pkgin.XXXX)"
#find ./pkgin.d -type f -exec cat \{\} >>$t \;
cat ./pkgin.d/pkgin.main.lst ./pkgin.d/pkgin.min.lst >>$t
pkgin -y import $t
rm $t

#for infi in $(find ./pkgin.d -type f) ; do
#  #[ -e $infi ] && pkgin -y import $infi
#  { set -x ; pkgin -y import $infi ;}
#done


exit 0

