#!/bin/sh

# REQUIRE: shell
# BEFORE:
# PROVIDE: pkgin
# KEYWORD: nbsd

set -e 

PKG_PATH="${URL_ROOT}/pkgsrc/packages/NetBSD/$(uname -m)/$(uname -r|cut -f 1-2 -d .| cut -f 1 -d _)/All"
PKG_PATH="${URL_ROOT}/pkgsrc/packages/NetBSD/$(uname -m)/$(uname -r|cut -f 1 -d _)/All"

PKGIN_CONF="/usr/pkg/etc/pkgin/repositories.conf"
PKG_EX="/usr/pkg/share/examples/pkgin/repositories.conf.example"
URL_ROOT="http://ftp.netbsd.org/pub/"
URL_BASE="${URL_ROOT}pkgsrc/packages/$(uname -s)/$(uname -m)/"
PKG_PATH="${URL_ROOT}pkgsrc/packages/NetBSD/\$arch/\$osrelease/All"
#PKG_REL="$(ftp -o - ${URL_BASE} \
#        | grep href | grep $(uname -r|cut -f 1 -d_) | grep -v _current \
#        | sed -e 's/.*href="//' -e 's/".*//' -e "s=^=# ${URL_BASE}=" \
#        -e "s/$/All/" )"
mkdir -p /usr/pkg/etc/pkgin
#[ -e "$PKGIN_CONF" ] || printf "# ${PKG_EX}\n${PKG_REL}\n${PKG_PATH}\n" >${PKGIN_CONF}

# http is intermitent today, ftp has been reliable....
URL_ROOT="ftp://ftp.netbsd.org/pub/"
PKG_PATH="${URL_ROOT}pkgsrc/packages/NetBSD/\$arch/\$osrelease/All"
printf "# ${PKG_EX}\n${PKG_REL}\n${PKG_PATH}\n" >${PKGIN_CONF}

PKG_PATH="ftp://ftp.netbsd.org/pub//pkgsrc/packages/NetBSD/amd64/8.0_2017Q2/All"
echo $PKG_PATH >$PKGIN_CONF
pkg_add $PKG_PATH/pkgin-0.9.4nb6.tgz # XXX
/usr/pkg/bin/pkgin -y update

#pkgin -y upgrade
#pkgin -y full-upgrade

cd $(dirname $0)
for e in ./pkgin.d/pkgin.main.lst ./pkgin.d/pkgin.min.lst ; do
        pkgin -y import $e
done

exit 0
