#!/bin/sh

# REQUIRE: 
# BEFORE:
# PROVIDE: rescue
# KEYWORD: nbsd

set -e 

URL_ROOT="https://cdn.netbsd.org/pub"
URL_BASE="NetBSD/NetBSD-$(uname -r|cut -f 1 -d _ )/$(uname -m)/binary/sets"
URL_COMP="${URL_ROOT}/${URL_BASE}/rescue.tar.xz"
DIST_PATH="/usr/local/dist/${URL_BASE}"
mkdir -p "$DIST_PATH"
ftp -o "${DIST_PATH}/rescue.tar.xz" "${URL_COMP}" \
  && cd / \
  && tar xzf "${DIST_PATH}/rescue.tar.xz"

exit 0
