#!/usr/bin/env python3

import sys
import string
# digs = string.digits + string.ascii_letters
# digs = "0123456789abcdefghijklmnpqrstuvwxyz"
# shift out characters "ilow" for visual acuity
#      "0123456789abcdefghijklmnpqrstuvwxyz"
digs = "0123456789abcdefghjkmnpqrstuvxyz"
def d2b(base,x):
    if x < 0:
        sign = -1
    elif x == 0:
        return digs[0]
    else:
        sign = 1

    x *= sign
    digits = []

    while x:
        digits.append(digs[int(x % base)])
        x = int(x / base)

    if sign < 0:
        digits.append('-')

    digits.reverse()

    return ''.join(digits)
# execute the decimal to base arg2 function
print(d2b(int(sys.argv[1]),int(sys.argv[2])))

